version: '3'

services:

  db:
    container_name: dashboard_db
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: dashboard_app
    env_file: ./.env
    command: /app/run_app.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: dashboard_nginx
    restart: always
    env_file: ./.env
    volumes:
      - ./app/static_root:/code/static_root
      - ./app/media:/code/media
      - ./nginx/logs:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


volumes:
  db_data: